name: Azure demoLive
on:
  push:
    branches:
      - toAzurev3

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
      - name: Autoriser à lire le repo
        uses: actions/checkout@v4
      - name: Configurer la JVM
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: alweare/demolive:1.0

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Déployer sur Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: devopsLive
          publish-profile: ${{ secrets.PUBLISH_PROFILE }} 
